### PR TITLE
Navigation slider

### PR DESCRIPTION
**Pull request by ApurvaSawant11**
Hello,

I have added navigation and slider to documentation site.

Please review and suggest

### CODE REVIEW

**Review by anik31 — APPROVED** [review]
Everything is very nice. Good work. I liked the slider component.
Suggestion - Add the javascript code to the docs as suggested in code reviews (You can do it later)

**Review by vishal804 — APPROVED** [review]

**Comment by vishal804** [comment]
Everything Looks Good

**Review by 05him — APPROVED** [review]
the slider and navigation looks good and code is also clean .
so its a good to go

**Comment by ApurvaSawant11** [comment]
> Everything is very nice. Good work. I liked the slider component. Suggestion - Add the javascript code to the docs as suggested in code reviews (You can do it later)

Thank you @anik31. I will add JS code as well in future PRs

**Pull request merged**
